# Default colors
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

# Cursor colors
[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#15161e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#b4befe"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

# Bright colors
[colors.bright]
black = "#414868"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#b4befe"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
